name: 🔄 Fetch and Cache F1 Docs

on:
  schedule:
    # should run every 8 hours
    - cron: "0 */8 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      date:
        description: "Date to run the workflow"
        required: true
        type: string
        default: "in 1 hour"
concurrency:
  group: schedule${{ github.event.inputs.date }}
  cancel-in-progress: true

jobs:
  update-cache:
    runs-on: ubuntu-latest
    env:
      CACHE_TOKEN: ${{ secrets.CACHE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Fetch and update grand prix events
        run: bun run fetch-events

      - name: Run cache regeneration
        run: bun scripts/fetch-all.ts
      
      - name: Run file download script
        run: bun fetch

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Jonathan Canevese
          author_email: work@jcanevese.it
          message: "Aggiornata cache F1"
          add: "*.json"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      # - name: Push changes
      #   uses: actions/checkout@v4
      # run: railway up --ci --environment=$RAILWAY_ENVIRONMENT_ID --service=$RAILWAY_SERVICE_ID
